version: "3"
services:
  v2ray:
    image: v2ray/official
    hostname: v2ray
    container_name: v2ray
    restart: always
    command: ["v2ray","-config=/etc/v2ray/config.json"]
    ports:
      - 2087:1087
      - 2087:1087/udp
    volumes:
      - ./:/etc/v2ray
